# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 410c5486a80147525fa6f88c8cf664b5e0bc653a836cbf79fdd87584b9037688ad694aac969ae49ec0144d288a53a743588f13043d6a530b9ff7e406d824b605

test:
  secret_key_base: eabebaf87e94277eeb34f662293fea853318dc6b3f211314d7ef101c3453320972938e15a46c3c042356b018efc3382bbd8bf98a03384013dc4c73d48feb8046

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
